amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    laser_model_type: "likelihood_field"
    transform_tolerance: 1.0
    initial_pose_x: 0.0
    initial_pose_y: 0.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      robot_base_frame: "base_footprint"
      global_frame: "map"
      rolling_window: false
      transform_tolerance: 1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      robot_base_frame: "base_footprint"
      global_frame: "odom"
      rolling_window: true
      transform_tolerance: 1.0

